# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lAN0HA4HYrWybD0CEMKRohMRZpr2iV7f
"""

import streamlit as st

def max_value(first, second, third):
  return max(first, second, third)

#Title
st.title("Max of three numbers")

#Input values
first = st.number_input("First number", value = 0)
second = st.number_input("Second number", value = 0)
third = st.number_input("Third number", value = 0)

#Button
if st.button("Max value of numbers"):
    largest_num = max_value(first, second, third)
    st.write(f"The largest number is {largest_num}")
